name: Keep Heroku Awake

on:
  schedule:
    - cron: "*/30 10-16 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: mikeesto/heroku-awake@1.0.0
        with:
          URL: "https://playlist-hunt.herokuapp.com" # ADD YOUR HEROKU URL HERE e.g. https://cats.herokuapp.com
